services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: oszford_db          # ← Cambiar de titanic_db
      MYSQL_USER: oszford_user            # ← Cambiar user
      MYSQL_PASSWORD: secure_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://oszford_user:secure_password@db:3306/oszford_db
    depends_on:
      - db

volumes:
  db_data: